version: '3.8'
services:
  train:
    build:
      context: .
      dockerfile: Dockerfile.train
    volumes:
      - ./pipelines/train/data:/usr/src/data
      - ./models/new:/usr/src/new_trained_models
  backend:
    build:
      context: .
      dockerfile: Dockerfile.detection
    volumes:
      - ./pipelines/detection/outputs:/usr/src/outputs
